sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - 8
  - 10
branches:
  only:
  - master
install:
- npm install
script:
  - npm run test
after_success:
- cat ./coverage/lcov.info | coveralls
